name: Publish image to container registry

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Install Pack CLI
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      - name: Push Image
        run: |
          pack build ghcr.io/duran91/demodeploy:latest \
            --builder paketobuildpacks/builder:base \
            --path . \
            --env "BP_OCI_SOURCE=https://github.com/duran91/demodeploy" \
            --publish

  deploy:
    needs: build_and_publish
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_AUTH_TOKEN }}
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy code
        run: flyctl deploy --image ghcr.io/duran91/demodeploy:latest


