name: Publish image to container registry

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          export CR_PAT=${{ secrets.GIT_HUB_PERSONAL_ACCESS_TOKEN }}
          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin
          pack build ghcr.io/duran91/demodeploy:latest \
            --builder paketobuildpacks/builder:base \
            --path . \
            --env "BP_OCI_SOURCE=https://github.com/duran91/demodeploy" \
            --publish


